### ISSUE TITLE
While instead of if?

### ISSUE THREAD

**Issue by fschlueter** [cg-laser/radiotools#7]
Hi @cg-laser,
is there a reason why using while in the code below:
### helpers.py:
`def get_normalized_angle(angle, degree=False, interval=np.deg2rad([0, 360])):
    import collections
    if degree:
        interval = np.rad2deg(interval)
    delta = interval[1] - interval[0]
    if(isinstance(angle, (collections.Sequence, np.ndarray))):
        angle[angle >= interval[1]] -= delta
        angle[angle < interval[0]] += delta
    else:
        while (angle >= interval[1]):
            angle -= delta
        while (angle < interval[0]):
            angle += delta
return angle`

PS: is there a better way to reference code from the repo?

**Comment by cg-laser** [comment]
A like to the code? Your snipplet is unreadable ;-)
https://github.com/nu-radio/radiotools/blob/master/radiotools/helper.py#L120-L133

Or just code tags (three ticks), more details here: https://guides.github.com/features/mastering-markdown/

The reason to use while instead of if is because the offset could also be larger than 2pi.

**Comment by fschlueter** [comment]
Ah yes a link looks good, i actually used 3 ticks, no idea why it did not worked.

**Comment by fschlueter** [comment]
Ah yes a link looks good, i actually used 3 ticks, no idea why it did not worked.

Ah okay I see. but this will not work when angles in an array  have a larger offset than 2 pi?

**Comment by cg-laser** [comment]
yes correct, I don't know how to implement this efficiently for arrays. I should probably add a proper description of the function
